chore: fixed docs workflow

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -29,14 +29,23 @@ jobs:
         run: |
           npm run docs:build
 
+          BRANCH="${GITHUB_REF_NAME}"
+          echo "Branch name : ${BRANCH}"
+          BRANCH_SAFE=$(echo "$BRANCH" | tr '/ #' '---' | sed 's/[^A-Za-z0-9._-]/-/g')
+
+          export DOCS_BASE="/lynjs/${BRANCH_SAFE}"
+          npm run docs:build
+
           mkdir -p "out/${BRANCH_SAFE}"
-          cp -r docs/dist/* "out/"
+          cp -r docs/dist/* "out/${BRANCH_SAFE}/"
+
+          echo "BRANCH_SAFE=${BRANCH_SAFE}" >> $GITHUB_ENV
 
       - name: Debug artifact tree
         run: |
           echo "== list out =="
           find out -maxdepth 3 -type f | sort
-          test -f "out/index.html" || (echo "index.html missing"; exit 1)
+          test -f "out/${BRANCH_SAFE}/index.html" || (echo "index.html missing"; exit 1)
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
